# hostname
# Autogenerated from man page /usr/share/man/man1/hostname.1
complete -c hostname -l help -d 'display this help and exit'
complete -c hostname -l version -d 'output version information and exit AUTHOR Written by Jim Meyering'

