# meinproc6
# Autogenerated from man page /usr/share/man/man1/meinproc6.1
complete -c meinproc6 -o h--help
complete -c meinproc6 -o v--version
complete -c meinproc6 -l cache
complete -c meinproc6 -l check
complete -c meinproc6 -s o -l output
complete -c meinproc6 -l stdout
complete -c meinproc6 -l stylesheet
complete -c meinproc6 -l srcdir
complete -c meinproc6 -l param

