# modules-load
# Autogenerated from man page /usr/share/man/man8/modules-load.8
complete -c modules-load -s n -d 'dry-run mode'
complete -c modules-load -s v -d 'verbose mode.  Print messages about what the program is doing'

