# pw-v4l2
# Autogenerated from man page /usr/share/man/man1/pw-v4l2.1
complete -c pw-v4l2 -s h -d 'Show help'
complete -c pw-v4l2 -s r -d 'The name of the remote instance to connect to'
complete -c pw-v4l2 -s v -d 'Verbose operation'

