# util-linux-logger
# Autogenerated from man page /usr/share/man/man1/util-linux-logger.1
complete -c util-linux-logger -s d -l udp
complete -c util-linux-logger -s e -l skip-empty
complete -c util-linux-logger -s f -l file
complete -c util-linux-logger -s i
complete -c util-linux-logger -l id
complete -c util-linux-logger -l journald
complete -c util-linux-logger -l msgid
complete -c util-linux-logger -s n -l server
complete -c util-linux-logger -l no-act
complete -c util-linux-logger -l octet-count
complete -c util-linux-logger -s P -l port
complete -c util-linux-logger -s p -l priority
complete -c util-linux-logger -l prio-prefix
complete -c util-linux-logger -l rfc3164
complete -c util-linux-logger -l rfc5424
complete -c util-linux-logger -s s -l stderr
complete -c util-linux-logger -l sd-id
complete -c util-linux-logger -l sd-param
complete -c util-linux-logger -s S -l size
complete -c util-linux-logger -l socket-errors
complete -c util-linux-logger -s T -l tcp
complete -c util-linux-logger -s t -l tag
complete -c util-linux-logger -s u -l socket
complete -c util-linux-logger -s h -l help
complete -c util-linux-logger -s V -l version

