# fsfreeze
# Autogenerated from man page /usr/share/man/man8/fsfreeze.8
complete -c fsfreeze -s f -l freeze
complete -c fsfreeze -s u -l unfreeze
complete -c fsfreeze -s h -l help
complete -c fsfreeze -s V -l version

