# ntpd
# Autogenerated from man page /usr/share/man/man8/ntpd.8
complete -c ntpd -s 4
complete -c ntpd -s 6
complete -c ntpd -s f
complete -c ntpd -s n
complete -c ntpd -s d
complete -c ntpd -s l
complete -c ntpd -s L
complete -c ntpd -s p
complete -c ntpd -s q
complete -c ntpd -s Q
complete -c ntpd -s r
complete -c ntpd -s R
complete -c ntpd -s s
complete -c ntpd -s t
complete -c ntpd -s u
complete -c ntpd -s U
complete -c ntpd -s F
complete -c ntpd -s P
complete -c ntpd -s m
complete -c ntpd -s x
complete -c ntpd -s v -l version
complete -c ntpd -s h -l help

