# pick
# Autogenerated from man page /usr/share/man/man1/pick.1
complete -c pick -s d -d 'Read and display descriptions'
complete -c pick -s K -d 'Disable toggling of keypad transmit mode'
complete -c pick -s o -d 'Output description of selected choice on exit'
complete -c pick -s q -d 'Supply an initial search query'
complete -c pick -s S -d 'Disable sorting'
complete -c pick -s x -d 'Enable the use of the alternate screen terminal feature.  This is the default'
complete -c pick -s X -d 'Disable the use of the alternate screen terminal feature'

