# void-docs
# Autogenerated from man page /usr/share/man/man1/void-docs.1
complete -c void-docs -s h -d 'Show help message'
complete -c void-docs -s b -d 'Only try to display the HTML version'
complete -c void-docs -s m -d 'Only try to display the Markdown version'
complete -c void-docs -s r -d 'Only try to display the roff (mdoc) version'
complete -c void-docs -s p -d 'Open the PDF version'
complete -c void-docs -s s -d 'Only display search results'

