# voikkovfstc
# Autogenerated from man page /usr/share/man/man1/voikkovfstc.1
complete -c voikkovfstc -s o -d 'Specify name for output file'
complete -c voikkovfstc -s f -d 'Specify format for output file'
complete -c voikkovfstc -s w -d 'Produce weighted transducers instead of unweighted transducers'

