# xmlcatmgr
# Autogenerated from man page /usr/share/man/man1/xmlcatmgr.1
complete -c xmlcatmgr -s c -d 'Use catalog as the catalog file'
complete -c xmlcatmgr -s h -d 'Show a descriptive usage message and exit'
complete -c xmlcatmgr -s p -d 'When adding a new entry to a catalog (using the add action), prepend it inste…'
complete -c xmlcatmgr -s s -d 'Use the standard SGML catalog format to parse the catalog, instead of the XML…'
complete -c xmlcatmgr -s v -d 'Show version information and exit'

