# XDG
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
# Aquamarine
env = AQ_NO_MODIFIERS,1
# App's
env = KITTY_ENABLE_WAYLAND,1
env = EDITOR,vim
# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# GDK
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland
env = GDK_SCALE,1
