env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = QT_QPA_PLATFORM,wayland;xcb
env = AQ_NO_MODIFIERS,1

env = KITTY_ENABLE_WAYLAND,1
env = EDITOR,vim
