windowrule = float on, persistent_size on, match:class nm-connection-editor
windowrule = float on, persistent_size on, match:class waypaper
windowrule = float on, persistent_size on, match:class nwg-look
windowrule = float on, persistent_size on, match:class qt6ct
windowrule = float on, persistent_size on, match:class galculator
windowrule = float on, size 300 150, match:initial_class colorpicker.sh
windowrule = float on, size 850 600, match:initial_class floating
windowrule = float on, size 1300 950, match:initial_class wttr.sh
windowrule = tile on, match:class vivaldi-stable
windowrule = idle_inhibit fullscreen, match:class vivaldi-stable
windowrule = idle_inhibit fullscreen, match:class mpv

layerrule = blur on, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace logout_dialog
layerrule {
	name = waybar
	blur = on
	xray = 1
	ignore_alpha = a=0.01
	match:namespace = waybar
}
